In [1]:
import numpy as np

In [2]:
x = np.array([45,32,56,78,12])

In [3]:
x

array([45, 32, 56, 78, 12])

In [4]:
print(x)

[45 32 56 78 12]


In [5]:
x[1]

32

In [6]:
y = np.array([45,32,56,78,12,'Aditya',43.21])

In [7]:
y

array(['45', '32', '56', '78', '12', 'Aditya', '43.21'], dtype='<U32')

In [10]:
%%timeit
y = np.array([45,32,56,78,12,'Aditya',43.21])

1.85 µs ± 82.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [11]:
%%timeit
z = [45,32,56,78,12,'Aditya',43.21]

51.8 ns ± 7.41 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [12]:
x = np.array([45,32,56,78,12])

In [13]:
x + 20

array([65, 52, 76, 98, 32])

In [14]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(5,20,2.5)

array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5])

In [17]:
list(range(5,20,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [19]:
np.arange(-5,5,2.5)

array([-5. , -2.5,  0. ,  2.5])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
x

array([45, 32, 56, 78, 12])

In [23]:
x.ndim

1

In [25]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [26]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
y.shape

(4, 3)

In [28]:
y.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
y.flatten().ndim

1

In [30]:
y.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
y.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [32]:
y.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [33]:
y.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
y.reshape(2,2,3).ndim

3

In [35]:
x

array([45, 32, 56, 78, 12])

In [36]:
x[1]

32

In [38]:
x[1:4]

array([32, 56, 78])

In [39]:
x[1:]

array([32, 56, 78, 12])

In [40]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
y[1:3,1:]

array([[5, 6],
       [8, 9]])

In [42]:
y[:,0:2]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [43]:
a = np.array([3,45,66,78,3,3,7])

In [47]:
np.unique(a)

array([ 3,  7, 45, 66, 78])

In [48]:
np.max(a)

78

In [49]:
np.mean(a)

29.285714285714285

In [50]:
np.median(a)

7.0