In [1]:
import numpy as np

In [2]:
arr1 = np.array([45,32,45,67,76])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2 = np.array([32,34,565,'Aditya',43.22])

In [5]:
arr2

array(['32', '34', '565', 'Aditya', '43.22'], dtype='<U32')

In [6]:
arr1.ndim

1

In [7]:
arr1

array([45, 32, 45, 67, 76])

In [8]:
arr1[1]

32

In [9]:
arr1 + 10

array([55, 42, 55, 77, 86])

In [10]:
arr1 / 2

array([22.5, 16. , 22.5, 33.5, 38. ])

In [11]:
x = np.arange(10)

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,10,.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [16]:
np.arange(10, 5, -0.5)

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [20]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
x.shape

(4, 3)

In [23]:
x.ndim

2

In [24]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
x.flatten().ndim

1

In [26]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
x.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
x.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [29]:
x.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [30]:
x.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [31]:
x.reshape(3,2,2).ndim

3

In [33]:
arr1

array([45, 32, 45, 67, 76])

In [40]:
arr1[::2]

array([45, 45, 76])

In [35]:
arr1[1:]

array([32, 45, 67, 76])

In [36]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
x[1:3,:2]

array([[4, 5],
       [7, 8]])

In [41]:
x[0:4,1:3]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [42]:
arr1

array([45, 32, 45, 67, 76])

In [43]:
np.unique(arr1)

array([32, 45, 67, 76])

In [44]:
np.linalg.matrix_rank(arr2)

/home/aditya/anaconda3/lib/python3.11/site-packages/numpy/linalg/linalg.py:1882: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return int(not all(A==0))


1